apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ray
  template:
    metadata:
      labels:
        app: ray
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: ray
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "6a0acd35-6d5b-42b2-b9e1-ffd0112686a8"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "6a0acd35-6d5b-42b2-b9e1-ffd0112686a8"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
